server :
  port : 8099
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dg.main.Entity  #扫描实体类,配置xml的别名
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除配置
      logic-not-delete-value: 1 #删除前jdbc:mysql://192.168.2.172:3306/diangou?useSSL=false&serverTimezone=UTC
      logic-delete-value: 0  #删除后jdbc:mysql://120.78.179.177:3306/test?characterEncoding=UTF-8&serverTimezone=GMT%2B8
spring:
  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      enabled: true
      encoding: utf-8
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    url: jdbc:mysql://192.168.2.172:3306/student?useSSL=FALSE&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 30000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    host: 192.168.2.225
    port: 9756
    timeout: 500
    jedis:
      pool:
        max-idle: 1000
        max-wait: 0
        min-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
  mvc:
    static-path-pattern: /**
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.2.172:9300

  #es :
  #host : 192.168.2.172  #192.168.2.158 #119.23.236.111
  #schema : http
  #port : 9200
  rabbitmq:
    host: 192.168.2.172
    port: 5672
    username: admin
    password: 123
    virtual-host: dgkj